/**
 * ISO2, E.164 dial, English label. Russia (RU) and Kazakhstan (KZ) excluded by product choice.
 * `COUNTRY_PHONE_OPTIONS` — alphabetical by label for search/dropdown.
 * `COUNTRY_PHONE_OPTIONS_FOR_PARSE` — longest dial first so `splitPhoneToDialNational` matches correctly.
 */
const RAW = [
  { iso: "AF", dial: "+93", label: "Afghanistan" },
  { iso: "AL", dial: "+355", label: "Albania" },
  { iso: "DZ", dial: "+213", label: "Algeria" },
  { iso: "AD", dial: "+376", label: "Andorra" },
  { iso: "AO", dial: "+244", label: "Angola" },
  { iso: "AR", dial: "+54", label: "Argentina" },
  { iso: "AM", dial: "+374", label: "Armenia" },
  { iso: "AU", dial: "+61", label: "Australia" },
  { iso: "AT", dial: "+43", label: "Austria" },
  { iso: "AZ", dial: "+994", label: "Azerbaijan" },
  { iso: "BH", dial: "+973", label: "Bahrain" },
  { iso: "BD", dial: "+880", label: "Bangladesh" },
  { iso: "BY", dial: "+375", label: "Belarus" },
  { iso: "BE", dial: "+32", label: "Belgium" },
  { iso: "BZ", dial: "+501", label: "Belize" },
  { iso: "BJ", dial: "+229", label: "Benin" },
  { iso: "BT", dial: "+975", label: "Bhutan" },
  { iso: "BO", dial: "+591", label: "Bolivia" },
  { iso: "BA", dial: "+387", label: "Bosnia and Herzegovina" },
  { iso: "BW", dial: "+267", label: "Botswana" },
  { iso: "BR", dial: "+55", label: "Brazil" },
  { iso: "BN", dial: "+673", label: "Brunei" },
  { iso: "BG", dial: "+359", label: "Bulgaria" },
  { iso: "BF", dial: "+226", label: "Burkina Faso" },
  { iso: "BI", dial: "+257", label: "Burundi" },
  { iso: "KH", dial: "+855", label: "Cambodia" },
  { iso: "CM", dial: "+237", label: "Cameroon" },
  { iso: "CA", dial: "+1", label: "Canada" },
  { iso: "CV", dial: "+238", label: "Cape Verde" },
  { iso: "CF", dial: "+236", label: "Central African Republic" },
  { iso: "TD", dial: "+235", label: "Chad" },
  { iso: "CL", dial: "+56", label: "Chile" },
  { iso: "CN", dial: "+86", label: "China" },
  { iso: "CO", dial: "+57", label: "Colombia" },
  { iso: "KM", dial: "+269", label: "Comoros" },
  { iso: "CG", dial: "+242", label: "Congo" },
  { iso: "CD", dial: "+243", label: "Congo (DRC)" },
  { iso: "CR", dial: "+506", label: "Costa Rica" },
  { iso: "CI", dial: "+225", label: "Côte d’Ivoire" },
  { iso: "HR", dial: "+385", label: "Croatia" },
  { iso: "CU", dial: "+53", label: "Cuba" },
  { iso: "CY", dial: "+357", label: "Cyprus" },
  { iso: "CZ", dial: "+420", label: "Czechia" },
  { iso: "DK", dial: "+45", label: "Denmark" },
  { iso: "DJ", dial: "+253", label: "Djibouti" },
  { iso: "DO", dial: "+1", label: "Dominican Republic" },
  { iso: "EC", dial: "+593", label: "Ecuador" },
  { iso: "EG", dial: "+20", label: "Egypt" },
  { iso: "SV", dial: "+503", label: "El Salvador" },
  { iso: "EE", dial: "+372", label: "Estonia" },
  { iso: "SZ", dial: "+268", label: "Eswatini" },
  { iso: "ET", dial: "+251", label: "Ethiopia" },
  { iso: "FJ", dial: "+679", label: "Fiji" },
  { iso: "FI", dial: "+358", label: "Finland" },
  { iso: "FR", dial: "+33", label: "France" },
  { iso: "GA", dial: "+241", label: "Gabon" },
  { iso: "GM", dial: "+220", label: "Gambia" },
  { iso: "GE", dial: "+995", label: "Georgia" },
  { iso: "DE", dial: "+49", label: "Germany" },
  { iso: "GH", dial: "+233", label: "Ghana" },
  { iso: "GR", dial: "+30", label: "Greece" },
  { iso: "GT", dial: "+502", label: "Guatemala" },
  { iso: "GN", dial: "+224", label: "Guinea" },
  { iso: "GW", dial: "+245", label: "Guinea-Bissau" },
  { iso: "GY", dial: "+592", label: "Guyana" },
  { iso: "HT", dial: "+509", label: "Haiti" },
  { iso: "HN", dial: "+504", label: "Honduras" },
  { iso: "HK", dial: "+852", label: "Hong Kong" },
  { iso: "HU", dial: "+36", label: "Hungary" },
  { iso: "IS", dial: "+354", label: "Iceland" },
  { iso: "IN", dial: "+91", label: "India" },
  { iso: "ID", dial: "+62", label: "Indonesia" },
  { iso: "IQ", dial: "+964", label: "Iraq" },
  { iso: "IE", dial: "+353", label: "Ireland" },
  { iso: "IL", dial: "+972", label: "Israel" },
  { iso: "IT", dial: "+39", label: "Italy" },
  { iso: "JM", dial: "+1", label: "Jamaica" },
  { iso: "JP", dial: "+81", label: "Japan" },
  { iso: "JO", dial: "+962", label: "Jordan" },
  { iso: "KE", dial: "+254", label: "Kenya" },
  { iso: "KW", dial: "+965", label: "Kuwait" },
  { iso: "KG", dial: "+996", label: "Kyrgyzstan" },
  { iso: "LA", dial: "+856", label: "Laos" },
  { iso: "LV", dial: "+371", label: "Latvia" },
  { iso: "LB", dial: "+961", label: "Lebanon" },
  { iso: "LS", dial: "+266", label: "Lesotho" },
  { iso: "LR", dial: "+231", label: "Liberia" },
  { iso: "LY", dial: "+218", label: "Libya" },
  { iso: "LI", dial: "+423", label: "Liechtenstein" },
  { iso: "LT", dial: "+370", label: "Lithuania" },
  { iso: "LU", dial: "+352", label: "Luxembourg" },
  { iso: "MO", dial: "+853", label: "Macao" },
  { iso: "MG", dial: "+261", label: "Madagascar" },
  { iso: "MW", dial: "+265", label: "Malawi" },
  { iso: "MY", dial: "+60", label: "Malaysia" },
  { iso: "MV", dial: "+960", label: "Maldives" },
  { iso: "ML", dial: "+223", label: "Mali" },
  { iso: "MT", dial: "+356", label: "Malta" },
  { iso: "MR", dial: "+222", label: "Mauritania" },
  { iso: "MU", dial: "+230", label: "Mauritius" },
  { iso: "MX", dial: "+52", label: "Mexico" },
  { iso: "MD", dial: "+373", label: "Moldova" },
  { iso: "MC", dial: "+377", label: "Monaco" },
  { iso: "MN", dial: "+976", label: "Mongolia" },
  { iso: "ME", dial: "+382", label: "Montenegro" },
  { iso: "MA", dial: "+212", label: "Morocco" },
  { iso: "MZ", dial: "+258", label: "Mozambique" },
  { iso: "MM", dial: "+95", label: "Myanmar" },
  { iso: "NA", dial: "+264", label: "Namibia" },
  { iso: "NP", dial: "+977", label: "Nepal" },
  { iso: "NL", dial: "+31", label: "Netherlands" },
  { iso: "NZ", dial: "+64", label: "New Zealand" },
  { iso: "NI", dial: "+505", label: "Nicaragua" },
  { iso: "NE", dial: "+227", label: "Niger" },
  { iso: "NG", dial: "+234", label: "Nigeria" },
  { iso: "MK", dial: "+389", label: "North Macedonia" },
  { iso: "NO", dial: "+47", label: "Norway" },
  { iso: "OM", dial: "+968", label: "Oman" },
  { iso: "PK", dial: "+92", label: "Pakistan" },
  { iso: "PS", dial: "+970", label: "Palestine" },
  { iso: "PA", dial: "+507", label: "Panama" },
  { iso: "PG", dial: "+675", label: "Papua New Guinea" },
  { iso: "PY", dial: "+595", label: "Paraguay" },
  { iso: "PE", dial: "+51", label: "Peru" },
  { iso: "PH", dial: "+63", label: "Philippines" },
  { iso: "PL", dial: "+48", label: "Poland" },
  { iso: "PT", dial: "+351", label: "Portugal" },
  { iso: "QA", dial: "+974", label: "Qatar" },
  { iso: "RO", dial: "+40", label: "Romania" },
  { iso: "RW", dial: "+250", label: "Rwanda" },
  { iso: "SA", dial: "+966", label: "Saudi Arabia" },
  { iso: "SN", dial: "+221", label: "Senegal" },
  { iso: "RS", dial: "+381", label: "Serbia" },
  { iso: "SC", dial: "+248", label: "Seychelles" },
  { iso: "SL", dial: "+232", label: "Sierra Leone" },
  { iso: "SG", dial: "+65", label: "Singapore" },
  { iso: "SK", dial: "+421", label: "Slovakia" },
  { iso: "SI", dial: "+386", label: "Slovenia" },
  { iso: "SO", dial: "+252", label: "Somalia" },
  { iso: "ZA", dial: "+27", label: "South Africa" },
  { iso: "KR", dial: "+82", label: "South Korea" },
  { iso: "SS", dial: "+211", label: "South Sudan" },
  { iso: "ES", dial: "+34", label: "Spain" },
  { iso: "LK", dial: "+94", label: "Sri Lanka" },
  { iso: "SD", dial: "+249", label: "Sudan" },
  { iso: "SR", dial: "+597", label: "Suriname" },
  { iso: "SE", dial: "+46", label: "Sweden" },
  { iso: "CH", dial: "+41", label: "Switzerland" },
  { iso: "TW", dial: "+886", label: "Taiwan" },
  { iso: "TJ", dial: "+992", label: "Tajikistan" },
  { iso: "TZ", dial: "+255", label: "Tanzania" },
  { iso: "TH", dial: "+66", label: "Thailand" },
  { iso: "TG", dial: "+228", label: "Togo" },
  { iso: "TT", dial: "+1", label: "Trinidad and Tobago" },
  { iso: "TN", dial: "+216", label: "Tunisia" },
  { iso: "TR", dial: "+90", label: "Türkiye" },
  { iso: "TM", dial: "+993", label: "Turkmenistan" },
  { iso: "UG", dial: "+256", label: "Uganda" },
  { iso: "UA", dial: "+380", label: "Ukraine" },
  { iso: "AE", dial: "+971", label: "United Arab Emirates" },
  { iso: "GB", dial: "+44", label: "United Kingdom" },
  { iso: "US", dial: "+1", label: "United States" },
  { iso: "UY", dial: "+598", label: "Uruguay" },
  { iso: "UZ", dial: "+998", label: "Uzbekistan" },
  { iso: "VE", dial: "+58", label: "Venezuela" },
  { iso: "VN", dial: "+84", label: "Vietnam" },
  { iso: "YE", dial: "+967", label: "Yemen" },
  { iso: "ZM", dial: "+260", label: "Zambia" },
  { iso: "ZW", dial: "+263", label: "Zimbabwe" },
];

/** Longest dial first; stable tie-break for shared codes (e.g. +1). */
export const COUNTRY_PHONE_OPTIONS_FOR_PARSE = [...RAW].sort((a, b) => {
  const len = b.dial.length - a.dial.length;
  if (len !== 0) return len;
  if (a.dial !== b.dial) return a.dial.localeCompare(b.dial);
  return a.iso.localeCompare(b.iso);
});

export const COUNTRY_PHONE_OPTIONS = [...RAW].sort((a, b) =>
  a.label.localeCompare(b.label, "en", { sensitivity: "base" }),
);
