apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: webchat-dev
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: webchat/user-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: webchat-secrets
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: webchat-secrets
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: webchat-secrets
                  key: POSTGRES_DB
            - name: EUREKA_URL
              value: http://discovery-service:8761/eureka/
            - name: EUREKA_INSTANCE_HOSTNAME
              value: user-service
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: webchat-secrets
                  key: JWT_SECRET
            - name: GATEWAY_INTERNAL_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: webchat-secrets
                  key: GATEWAY_INTERNAL_AUTH_TOKEN
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 90
            periodSeconds: 20
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
