apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: webchat-dev
  labels:
    app: mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
