apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: webchat-dev
  labels:
    app: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 8089
      targetPort: 8089
  type: ClusterIP
