apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chat-uploads
  namespace: webchat-dev
  labels:
    app: chat-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
