apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: webchat-dev
  labels:
    app: chat-service
spec:
  selector:
    app: chat-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
  type: ClusterIP
